

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/faap
    driverClassName: org.postgresql.Driver
    username: faap
    password: mysecretpassword
    testWhileIdle: true
    validationQuery: SELECT 1
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:faap;
    driverClassName: org.h2.Driver
    username: faap
    password: mysecretpassword
    testWhileIdle: true
    validationQuery: SELECT 1
---
flyway:
  locations: db/migration/V1_1__create_employee.sql