

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/faap
    driverClassName: org.postgresql.Driver
    username: faap
    password: mysecretpassword
    testWhileIdle: true
    validationQuery: SELECT 1